apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
      - name: fast-api
        image: josesantiagowolff/hello-app:e68512a77a85774b4f630ba0844be6140030e356
        resources:
          limits:
            memory: "256Mi"          
            cpu: "500m"
        ports:
        - containerPort: 8000