apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josewolffsantiago/CompassUOL-CI-CD-ArgoCD-Sprint6-PBJUN2025-DevSecOPs.git
    path: /gitops-microservices/k8s
    targetRevision: HEAD
    helm:
     valueFiles:
       - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true