apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fast-api
  labels:
    release: monitoring  # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app: fast-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default